
platform :ios, '7.0'

pod 'AFNetworking', '~> 2.5.3'
pod 'SVProgressHUD', '~> 1.0'
pod 'SDWebImage', '~> 3.7.1'
pod 'MJExtension', '~> 2.0.1'
pod 'MJRefresh', '~> 1.4.5'
pod 'PureLayout', '~> 2.0.6'
pod 'CHTCollectionViewWaterfallLayout', '~> 0.8'
pod 'ZBarSDK', '~> 1.3.1'
pod 'NJKWebViewProgress', '~> 0.2.3'
pod 'Masonry', '~> 0.6.2'


